package gazelle_pyproject

import (
	"log"

	"github.com/bazelbuild/bazel-gazelle/config"
	"github.com/bazelbuild/bazel-gazelle/label"
	"github.com/bazelbuild/bazel-gazelle/repo"
	"github.com/bazelbuild/bazel-gazelle/resolve"
	"github.com/bazelbuild/bazel-gazelle/rule"
	"github.com/emirpasic/gods/sets/treeset"
)

const (
	// resolvedDepsKey is the attribute key used to pass dependencies that don't
	// need to be resolved by the dependency resolver in the Resolver step.
	resolvedDepsKey = "_gazelle_python_resolved_deps"
)

const languageName = "py"

type Resolver struct {
}

// Name returns the name of the language. This is the prefix of the kinds of
// rules generated. E.g. py_library and py_binary.
func (*Resolver) Name() string { return languageName }

// Imports returns a list of ImportSpecs that can be used to import the rule
// r. This is used to populate RuleIndex.
//
// If nil is returned, the rule will not be indexed. If any non-nil slice is
// returned, including an empty slice, the rule will be indexed.
func (py *Resolver) Imports(c *config.Config, r *rule.Rule, f *rule.File) []resolve.ImportSpec {
	log.Printf("Imports called for %s", r.Name())
	provides := make([]resolve.ImportSpec, 0, 1)
	importSpec := resolve.ImportSpec{
		Lang: languageName,
		Imp:  r.Name(),
	}
	provides = append(provides, importSpec)
	return provides
}

// Embeds returns a list of labels of rules that the given rule embeds. If
// a rule is embedded by another importable rule of the same language, only
// the embedding rule will be indexed. The embedding rule will inherit
// the imports of the embedded rule.
func (py *Resolver) Embeds(r *rule.Rule, from label.Label) []label.Label {
	// TODO(f0rmiga): implement.
	log.Printf("Embeds called for %s", r.Name())
	return make([]label.Label, 0)
}

// Resolve translates imported libraries for a given rule into Bazel
// dependencies. Information about imported libraries is returned for each
// rule generated by language.GenerateRules in
// language.GenerateResult.Imports. Resolve generates a "deps" attribute (or
// the appropriate language-specific equivalent) for each import according to
// language-specific rules and heuristics.
func (py *Resolver) Resolve(
	c *config.Config,
	ix *resolve.RuleIndex,
	rc *repo.RemoteCache,
	r *rule.Rule,
	modulesRaw interface{},
	from label.Label,
) {
	log.Printf("Resolve called for %s", r.Name())
	deps := treeset.NewWithStringComparator()
	if modulesRaw != nil {
		requirements := modulesRaw.([]string)
		for _, requirement := range requirements {
			imp := resolve.ImportSpec{Lang: languageName, Imp: requirement}
			log.Printf("imp: %s", imp.Imp)
			matches := ix.FindRulesByImportWithConfig(c, imp, languageName)
			if len(matches) > 0 {
				deps.Add(matches[0].Label.String())
			} else {
				// todo: this shouldn't be hardcoded to @pypi
				deps.Add("@pypi//" + requirement)
			}
		}
	}

	if resolvedDeps := r.PrivateAttr(resolvedDepsKey); resolvedDeps != nil {
		resolvedDeps := resolvedDeps.([]string)
		for _, resolvedDep := range resolvedDeps {
			deps.Add(resolvedDep)
		}
	}
	log.Printf("deps: %v", deps.Values())

	r.SetAttr("deps", deps.Values())
}
